/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AddRawMaterialRouteImport } from './routes/add-raw-material'
import { Route as AddDilutionRouteImport } from './routes/add-dilution'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManageDilutionsMaterialIdRouteImport } from './routes/manage-dilutions.$materialId'
import { Route as ApiRawMaterialsRouteImport } from './routes/api.raw-materials'
import { Route as ApiNotesRouteImport } from './routes/api.notes'
import { Route as ApiDilutionsRouteImport } from './routes/api.dilutions'
import { Route as ApiCategoriesRouteImport } from './routes/api.categories'

const AddRawMaterialRoute = AddRawMaterialRouteImport.update({
  id: '/add-raw-material',
  path: '/add-raw-material',
  getParentRoute: () => rootRouteImport,
} as any)
const AddDilutionRoute = AddDilutionRouteImport.update({
  id: '/add-dilution',
  path: '/add-dilution',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageDilutionsMaterialIdRoute =
  ManageDilutionsMaterialIdRouteImport.update({
    id: '/manage-dilutions/$materialId',
    path: '/manage-dilutions/$materialId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRawMaterialsRoute = ApiRawMaterialsRouteImport.update({
  id: '/api/raw-materials',
  path: '/api/raw-materials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotesRoute = ApiNotesRouteImport.update({
  id: '/api/notes',
  path: '/api/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDilutionsRoute = ApiDilutionsRouteImport.update({
  id: '/api/dilutions',
  path: '/api/dilutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesRoute = ApiCategoriesRouteImport.update({
  id: '/api/categories',
  path: '/api/categories',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-dilution': typeof AddDilutionRoute
  '/add-raw-material': typeof AddRawMaterialRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/dilutions': typeof ApiDilutionsRoute
  '/api/notes': typeof ApiNotesRoute
  '/api/raw-materials': typeof ApiRawMaterialsRoute
  '/manage-dilutions/$materialId': typeof ManageDilutionsMaterialIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-dilution': typeof AddDilutionRoute
  '/add-raw-material': typeof AddRawMaterialRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/dilutions': typeof ApiDilutionsRoute
  '/api/notes': typeof ApiNotesRoute
  '/api/raw-materials': typeof ApiRawMaterialsRoute
  '/manage-dilutions/$materialId': typeof ManageDilutionsMaterialIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-dilution': typeof AddDilutionRoute
  '/add-raw-material': typeof AddRawMaterialRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/dilutions': typeof ApiDilutionsRoute
  '/api/notes': typeof ApiNotesRoute
  '/api/raw-materials': typeof ApiRawMaterialsRoute
  '/manage-dilutions/$materialId': typeof ManageDilutionsMaterialIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-dilution'
    | '/add-raw-material'
    | '/api/categories'
    | '/api/dilutions'
    | '/api/notes'
    | '/api/raw-materials'
    | '/manage-dilutions/$materialId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-dilution'
    | '/add-raw-material'
    | '/api/categories'
    | '/api/dilutions'
    | '/api/notes'
    | '/api/raw-materials'
    | '/manage-dilutions/$materialId'
  id:
    | '__root__'
    | '/'
    | '/add-dilution'
    | '/add-raw-material'
    | '/api/categories'
    | '/api/dilutions'
    | '/api/notes'
    | '/api/raw-materials'
    | '/manage-dilutions/$materialId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddDilutionRoute: typeof AddDilutionRoute
  AddRawMaterialRoute: typeof AddRawMaterialRoute
  ApiCategoriesRoute: typeof ApiCategoriesRoute
  ApiDilutionsRoute: typeof ApiDilutionsRoute
  ApiNotesRoute: typeof ApiNotesRoute
  ApiRawMaterialsRoute: typeof ApiRawMaterialsRoute
  ManageDilutionsMaterialIdRoute: typeof ManageDilutionsMaterialIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/add-raw-material': {
      id: '/add-raw-material'
      path: '/add-raw-material'
      fullPath: '/add-raw-material'
      preLoaderRoute: typeof AddRawMaterialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-dilution': {
      id: '/add-dilution'
      path: '/add-dilution'
      fullPath: '/add-dilution'
      preLoaderRoute: typeof AddDilutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-dilutions/$materialId': {
      id: '/manage-dilutions/$materialId'
      path: '/manage-dilutions/$materialId'
      fullPath: '/manage-dilutions/$materialId'
      preLoaderRoute: typeof ManageDilutionsMaterialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/raw-materials': {
      id: '/api/raw-materials'
      path: '/api/raw-materials'
      fullPath: '/api/raw-materials'
      preLoaderRoute: typeof ApiRawMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notes': {
      id: '/api/notes'
      path: '/api/notes'
      fullPath: '/api/notes'
      preLoaderRoute: typeof ApiNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dilutions': {
      id: '/api/dilutions'
      path: '/api/dilutions'
      fullPath: '/api/dilutions'
      preLoaderRoute: typeof ApiDilutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories': {
      id: '/api/categories'
      path: '/api/categories'
      fullPath: '/api/categories'
      preLoaderRoute: typeof ApiCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddDilutionRoute: AddDilutionRoute,
  AddRawMaterialRoute: AddRawMaterialRoute,
  ApiCategoriesRoute: ApiCategoriesRoute,
  ApiDilutionsRoute: ApiDilutionsRoute,
  ApiNotesRoute: ApiNotesRoute,
  ApiRawMaterialsRoute: ApiRawMaterialsRoute,
  ManageDilutionsMaterialIdRoute: ManageDilutionsMaterialIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
