/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AddRawMaterialRouteImport } from './routes/add-raw-material'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRawMaterialsRouteImport } from './routes/api.raw-materials'
import { Route as ApiCategoriesRouteImport } from './routes/api.categories'

const AddRawMaterialRoute = AddRawMaterialRouteImport.update({
  id: '/add-raw-material',
  path: '/add-raw-material',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRawMaterialsRoute = ApiRawMaterialsRouteImport.update({
  id: '/api/raw-materials',
  path: '/api/raw-materials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesRoute = ApiCategoriesRouteImport.update({
  id: '/api/categories',
  path: '/api/categories',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-raw-material': typeof AddRawMaterialRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/raw-materials': typeof ApiRawMaterialsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-raw-material': typeof AddRawMaterialRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/raw-materials': typeof ApiRawMaterialsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-raw-material': typeof AddRawMaterialRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/raw-materials': typeof ApiRawMaterialsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-raw-material'
    | '/api/categories'
    | '/api/raw-materials'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add-raw-material' | '/api/categories' | '/api/raw-materials'
  id:
    | '__root__'
    | '/'
    | '/add-raw-material'
    | '/api/categories'
    | '/api/raw-materials'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRawMaterialRoute: typeof AddRawMaterialRoute
  ApiCategoriesRoute: typeof ApiCategoriesRoute
  ApiRawMaterialsRoute: typeof ApiRawMaterialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/add-raw-material': {
      id: '/add-raw-material'
      path: '/add-raw-material'
      fullPath: '/add-raw-material'
      preLoaderRoute: typeof AddRawMaterialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/raw-materials': {
      id: '/api/raw-materials'
      path: '/api/raw-materials'
      fullPath: '/api/raw-materials'
      preLoaderRoute: typeof ApiRawMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories': {
      id: '/api/categories'
      path: '/api/categories'
      fullPath: '/api/categories'
      preLoaderRoute: typeof ApiCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRawMaterialRoute: AddRawMaterialRoute,
  ApiCategoriesRoute: ApiCategoriesRoute,
  ApiRawMaterialsRoute: ApiRawMaterialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
