/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FormulasRouteImport } from './routes/formulas'
import { Route as AddRawMaterialRouteImport } from './routes/add-raw-material'
import { Route as AddFormulaRouteImport } from './routes/add-formula'
import { Route as AddFeedbackRouteImport } from './routes/add-feedback'
import { Route as AddDilutionRouteImport } from './routes/add-dilution'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManageDilutionsMaterialIdRouteImport } from './routes/manage-dilutions.$materialId'
import { Route as AuthPathnameRouteImport } from './routes/auth.$pathname'
import { Route as ApiRawMaterialsRouteImport } from './routes/api.raw-materials'
import { Route as ApiNotesRouteImport } from './routes/api.notes'
import { Route as ApiFormulasRouteImport } from './routes/api.formulas'
import { Route as ApiFeedbackRouteImport } from './routes/api.feedback'
import { Route as ApiDilutionsRouteImport } from './routes/api.dilutions'
import { Route as ApiCategoriesRouteImport } from './routes/api.categories'
import { Route as ApiAgentRawMaterialChatRouteImport } from './routes/api/agent/raw-material-chat'

const FormulasRoute = FormulasRouteImport.update({
  id: '/formulas',
  path: '/formulas',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRawMaterialRoute = AddRawMaterialRouteImport.update({
  id: '/add-raw-material',
  path: '/add-raw-material',
  getParentRoute: () => rootRouteImport,
} as any)
const AddFormulaRoute = AddFormulaRouteImport.update({
  id: '/add-formula',
  path: '/add-formula',
  getParentRoute: () => rootRouteImport,
} as any)
const AddFeedbackRoute = AddFeedbackRouteImport.update({
  id: '/add-feedback',
  path: '/add-feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AddDilutionRoute = AddDilutionRouteImport.update({
  id: '/add-dilution',
  path: '/add-dilution',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageDilutionsMaterialIdRoute =
  ManageDilutionsMaterialIdRouteImport.update({
    id: '/manage-dilutions/$materialId',
    path: '/manage-dilutions/$materialId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthPathnameRoute = AuthPathnameRouteImport.update({
  id: '/auth/$pathname',
  path: '/auth/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRawMaterialsRoute = ApiRawMaterialsRouteImport.update({
  id: '/api/raw-materials',
  path: '/api/raw-materials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotesRoute = ApiNotesRouteImport.update({
  id: '/api/notes',
  path: '/api/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFormulasRoute = ApiFormulasRouteImport.update({
  id: '/api/formulas',
  path: '/api/formulas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedbackRoute = ApiFeedbackRouteImport.update({
  id: '/api/feedback',
  path: '/api/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDilutionsRoute = ApiDilutionsRouteImport.update({
  id: '/api/dilutions',
  path: '/api/dilutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesRoute = ApiCategoriesRouteImport.update({
  id: '/api/categories',
  path: '/api/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRawMaterialChatRoute = ApiAgentRawMaterialChatRouteImport.update({
  id: '/api/agent/raw-material-chat',
  path: '/api/agent/raw-material-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-dilution': typeof AddDilutionRoute
  '/add-feedback': typeof AddFeedbackRoute
  '/add-formula': typeof AddFormulaRoute
  '/add-raw-material': typeof AddRawMaterialRoute
  '/formulas': typeof FormulasRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/dilutions': typeof ApiDilutionsRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/formulas': typeof ApiFormulasRoute
  '/api/notes': typeof ApiNotesRoute
  '/api/raw-materials': typeof ApiRawMaterialsRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/manage-dilutions/$materialId': typeof ManageDilutionsMaterialIdRoute
  '/api/agent/raw-material-chat': typeof ApiAgentRawMaterialChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-dilution': typeof AddDilutionRoute
  '/add-feedback': typeof AddFeedbackRoute
  '/add-formula': typeof AddFormulaRoute
  '/add-raw-material': typeof AddRawMaterialRoute
  '/formulas': typeof FormulasRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/dilutions': typeof ApiDilutionsRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/formulas': typeof ApiFormulasRoute
  '/api/notes': typeof ApiNotesRoute
  '/api/raw-materials': typeof ApiRawMaterialsRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/manage-dilutions/$materialId': typeof ManageDilutionsMaterialIdRoute
  '/api/agent/raw-material-chat': typeof ApiAgentRawMaterialChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-dilution': typeof AddDilutionRoute
  '/add-feedback': typeof AddFeedbackRoute
  '/add-formula': typeof AddFormulaRoute
  '/add-raw-material': typeof AddRawMaterialRoute
  '/formulas': typeof FormulasRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/dilutions': typeof ApiDilutionsRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/formulas': typeof ApiFormulasRoute
  '/api/notes': typeof ApiNotesRoute
  '/api/raw-materials': typeof ApiRawMaterialsRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/manage-dilutions/$materialId': typeof ManageDilutionsMaterialIdRoute
  '/api/agent/raw-material-chat': typeof ApiAgentRawMaterialChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-dilution'
    | '/add-feedback'
    | '/add-formula'
    | '/add-raw-material'
    | '/formulas'
    | '/api/categories'
    | '/api/dilutions'
    | '/api/feedback'
    | '/api/formulas'
    | '/api/notes'
    | '/api/raw-materials'
    | '/auth/$pathname'
    | '/manage-dilutions/$materialId'
    | '/api/agent/raw-material-chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-dilution'
    | '/add-feedback'
    | '/add-formula'
    | '/add-raw-material'
    | '/formulas'
    | '/api/categories'
    | '/api/dilutions'
    | '/api/feedback'
    | '/api/formulas'
    | '/api/notes'
    | '/api/raw-materials'
    | '/auth/$pathname'
    | '/manage-dilutions/$materialId'
    | '/api/agent/raw-material-chat'
  id:
    | '__root__'
    | '/'
    | '/add-dilution'
    | '/add-feedback'
    | '/add-formula'
    | '/add-raw-material'
    | '/formulas'
    | '/api/categories'
    | '/api/dilutions'
    | '/api/feedback'
    | '/api/formulas'
    | '/api/notes'
    | '/api/raw-materials'
    | '/auth/$pathname'
    | '/manage-dilutions/$materialId'
    | '/api/agent/raw-material-chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddDilutionRoute: typeof AddDilutionRoute
  AddFeedbackRoute: typeof AddFeedbackRoute
  AddFormulaRoute: typeof AddFormulaRoute
  AddRawMaterialRoute: typeof AddRawMaterialRoute
  FormulasRoute: typeof FormulasRoute
  ApiCategoriesRoute: typeof ApiCategoriesRoute
  ApiDilutionsRoute: typeof ApiDilutionsRoute
  ApiFeedbackRoute: typeof ApiFeedbackRoute
  ApiFormulasRoute: typeof ApiFormulasRoute
  ApiNotesRoute: typeof ApiNotesRoute
  ApiRawMaterialsRoute: typeof ApiRawMaterialsRoute
  AuthPathnameRoute: typeof AuthPathnameRoute
  ManageDilutionsMaterialIdRoute: typeof ManageDilutionsMaterialIdRoute
  ApiAgentRawMaterialChatRoute: typeof ApiAgentRawMaterialChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/formulas': {
      id: '/formulas'
      path: '/formulas'
      fullPath: '/formulas'
      preLoaderRoute: typeof FormulasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-raw-material': {
      id: '/add-raw-material'
      path: '/add-raw-material'
      fullPath: '/add-raw-material'
      preLoaderRoute: typeof AddRawMaterialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-formula': {
      id: '/add-formula'
      path: '/add-formula'
      fullPath: '/add-formula'
      preLoaderRoute: typeof AddFormulaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-feedback': {
      id: '/add-feedback'
      path: '/add-feedback'
      fullPath: '/add-feedback'
      preLoaderRoute: typeof AddFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-dilution': {
      id: '/add-dilution'
      path: '/add-dilution'
      fullPath: '/add-dilution'
      preLoaderRoute: typeof AddDilutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-dilutions/$materialId': {
      id: '/manage-dilutions/$materialId'
      path: '/manage-dilutions/$materialId'
      fullPath: '/manage-dilutions/$materialId'
      preLoaderRoute: typeof ManageDilutionsMaterialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$pathname': {
      id: '/auth/$pathname'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof AuthPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/raw-materials': {
      id: '/api/raw-materials'
      path: '/api/raw-materials'
      fullPath: '/api/raw-materials'
      preLoaderRoute: typeof ApiRawMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notes': {
      id: '/api/notes'
      path: '/api/notes'
      fullPath: '/api/notes'
      preLoaderRoute: typeof ApiNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/formulas': {
      id: '/api/formulas'
      path: '/api/formulas'
      fullPath: '/api/formulas'
      preLoaderRoute: typeof ApiFormulasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feedback': {
      id: '/api/feedback'
      path: '/api/feedback'
      fullPath: '/api/feedback'
      preLoaderRoute: typeof ApiFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dilutions': {
      id: '/api/dilutions'
      path: '/api/dilutions'
      fullPath: '/api/dilutions'
      preLoaderRoute: typeof ApiDilutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories': {
      id: '/api/categories'
      path: '/api/categories'
      fullPath: '/api/categories'
      preLoaderRoute: typeof ApiCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/raw-material-chat': {
      id: '/api/agent/raw-material-chat'
      path: '/api/agent/raw-material-chat'
      fullPath: '/api/agent/raw-material-chat'
      preLoaderRoute: typeof ApiAgentRawMaterialChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddDilutionRoute: AddDilutionRoute,
  AddFeedbackRoute: AddFeedbackRoute,
  AddFormulaRoute: AddFormulaRoute,
  AddRawMaterialRoute: AddRawMaterialRoute,
  FormulasRoute: FormulasRoute,
  ApiCategoriesRoute: ApiCategoriesRoute,
  ApiDilutionsRoute: ApiDilutionsRoute,
  ApiFeedbackRoute: ApiFeedbackRoute,
  ApiFormulasRoute: ApiFormulasRoute,
  ApiNotesRoute: ApiNotesRoute,
  ApiRawMaterialsRoute: ApiRawMaterialsRoute,
  AuthPathnameRoute: AuthPathnameRoute,
  ManageDilutionsMaterialIdRoute: ManageDilutionsMaterialIdRoute,
  ApiAgentRawMaterialChatRoute: ApiAgentRawMaterialChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
